language: node_js
node_js:
- 8.6.0
deploy:
  provider: heroku
  api_key:
    secure: ZiR5PA/UaAaJVdJH8Dlt5LTTi/naUiygBpZ6Wa8kF92c/Bbi2BQPD7FlsuVAhY8rP3lc9Y+LipT1o4zZPSd5bT+q3SCY9gU6+8M96hzmAxnt9LoPw8RtsNMapzFdi5YGUEVkffe6t+TNOWrmq7XnxaqNd4jnKAwsu0QPnfAkCdbJtRKofrYRI83n/ZbAJ271qYjAHHCRS/xwemBoZulyEJHgg/Yj24l8ZlwCTZ1uZUPrTkhayTh4Czxc4qOfgvYmMuLxElwEirhUCnFdXnRESNxxmVh0siQJSVwFv4X9OcheiXQHwP29jqo2oFcPcaOqwV9p2l01V5FHZ0trFdUwlT0h6mfWg505VEsEiJVbntxoQH3AgOz1l1bMv75WJTrnQdJ1DJ0tsHCFwuf4pUkkQGr8vKao0tFWYTYfbBTRv/HXjZu5wYY/PC40+dijg3cInMns/hNvnXTXwiCyJzMmTN+EU2rXzXR5g9a6r+PT4SePGxRDyanJfL7ZALsdOdrxdKLI4/5E2de3vdX3DqtEM0fcxjzeEog0ohAcl+N6JoTCgQBTgpIeZwbQrc3SXO+rtfeemO+yN4wrdIiaUevEGNKCl5ipUkiARuR6oezVmMnJgMKjGPeozSQvF8OKDM0Nis9VXev8anqCoc3upWNPUnT/bhUzqB6OXwyEy+6h7Uc=
  app:
    master: oudot-production
    develop: oudot-staging
