language: node_js
node_js:
- 8.6.0
deploy:
  provider: heroku
  api_key:
    secure: "WLQ+eSpq3XNGnlHA7wkxS6lrG93OOnqoX/EC4Agk+F7zC/GRfwokHYhdOHFfounfyyn2DAn4GRsDqLgCzvvxtMxI0b5fuF32NCKvVO6PUSskusYtzjMDwUD9/Z1s64UXuIqae7SkXPazn+z8c9ybTsSzWetemBxmOAGRetNhFsy7x5EzLnvc3d6DvJSf6R+33LVlKABTgpFCNfFfnrwhXqIFvBjMQdEDWPu+2Y/ohPcI+eVseKVrLcPci2HmorxyYkbrZHTwunZuXvAIUK+lwkqJru4tfjuIgBerUTktusut9OMn6rdduCR7ca594rTT2D5jEnIdBPf6q7MvZDX4Ecr6iuuiyXc8S3LisAPkyfwSUb2qnbB0k8RRFOP+9ZM7OXvWDrhKtL2/8GaYog+vr4mebF/AzQDGYQn1orWCKVr9iodWaLkF7BvT8r2sCRvbBJNWAr+BcbedYOfZ5d5v0ZanhlMyZtgg/Nv1zQq8pUdXMNDZx+CQxoj5Y/yU3VUDJfdQvr9HH6VAq1FnofxbN3zjddQPYghdf8i8Zu660TVLvGSnQZSMBcIEId3pGDRq/SvXtOzstvI4LvOb+5dr/I5kGypxpznd437D+NET/AJJX4hloT3f/jaKuQGaHZ9CSjCiD+DGhCuuoSsuNYJAWwlDkneWEPNPW/x+P1sVzZk="
  app:
    master: oudot-production
    develop: oudot-staging
